# these are all fake, and definitely should be changed in production.
secret_key_base: 5c57bad3e5bb6b32244088398d31ab7d27b7d2c66fdf03568eaf374424a57cfe40a01558210e5e5a044e6c4b139e396c9541ea5c400fa3899e684ea3f5ba15e6
devise_pepper: 5c57bad3e5bb6b32244088398d31ab7d27b7d2c66fdf03568eaf374424a57cfe40a01558210e5e5a044e6c4b139e396c9541ea5c400fa3899e684ea3f5ba15e6
gibbon_api_key: gibbonkey
country_code: US

mapbox:
  token: notarealtoken

airbrake:
  project_id: 12344
  key: supersecretkey
twilio:
  account_sid: fakesid
  auth_token: faketoken
  survey_number: 15555555555
  signup_number: 15455555552
mailchimp:
  api_key: notanapikey
  list_id: fffaaabbbooo
  webhook_secret_key: secretkey
neighborhood: NEW_YORK

mailer:
  sender: dig@brl.nyc
  admin: dig@brl.nyc

mandrill:
  ingress_api_key: not.a.key

smtp:
  host: smtp.mandrillapp.com
  port: 587
  username: Blue_Ridge
  password: supersecret
aws:
  api_token: bogustoken
  api_secret: bogussecret
  s3_bucket: bogusbucket

site:
  name: FoobarBazBat

google:
  analytics_id: BlargID
  maps_api: supertoken

rapidpro:
  token: supertoken
  domain: rapidpro.local
  web_address: https://textit.com

tremendous:
  org_id: the_fakest
  api_token: superfake
  endpoint: https://testflight.tremendous.com/api/v2/
  webhook: not_a_token
  campaigns:
    high: high_campaign_id
    low: low_campaign_id

skylight:
  auth: authtoken

community_lawyer:
  url: https://redirectme.to?token_id=

# this is bill cromie's public key. Enjoy!
backup_public_key: |-
  -----BEGIN PGP PUBLIC KEY BLOCK-----
  Version: GnuPG v1

  mQINBFYBlC4BEAD75wASVs35s7mpdzMtJ0QISCeGScS01pKjNIJH/I0H1AoFPFo/
  9MgRBlHe++qcBWGtj/3pJm/p2/QBJEBEXKfOtV0OsRpHQ2ErIPqv93cEGI4L/uMv
  Q2oE9BYO3DOvCIPPjiTj+aqa8CBA25gZi9QxI68+BUlhZsMxLopjBzhVXhVBhCL0
  wK9D5puIZy966Qzv00NjHTUcbLcBl8lqvZqXXJNDmQx0pgDMY5qzia8a6/MJx7Q9
  MbTiXYPzf9mti6PtKKBclC32r0jmaLbUHOZsuvDDFIP+mVTtO9RQSfAJ8GTU+xwU
  Gig2LCvmA1hZPSUPsfYPYglYK3BtD6hQQUGITD+GeY6nKZLxhj6gPaFhWTmqc8Mr
  Bg8NVvxhGNm8H3qBs+/YZpw1Y6+hDEgqg9sH3VoNmlTDPcLFNHgBL+RlIaSCq6zg
  kN6aggM6dDMVlPbeqxXUkRaevw3WaeNxHmH3axvmWJfAC+jBuPFtDPIdiI/2tKhe
  jG52zx1K0rxKFPFdilMqUZxESpzmlG00N3vzUGCdOZYqXvdEFyHVV8GevUK7MDkC
  Adwf31HYjyNbHFaUG48QSKbK3rINjLqbsOBh4A8CsfcqCmKhrUk17NBL8rUeFcZj
  RAJjk93vaox7S60Z03YWrzOuSLwPgXjcfTa+8lKqDPblYSr6ne4gcHf+DwARAQAB
  tCdrZXliYXNlLmlvL2Jjcm9taWUgPGJjcm9taWVAa2V5YmFzZS5pbz6JAj4EEwEC
  ACgFAlYBlC4CGyMFCRLMAwAGCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJEGv8
  pyAAarLe6mAP/itdBD8w+UWZBZV2wWCCs38vHdtBf4Tr78s4uFkCZczapC0DGWfT
  eMbdm9gAv82MLt43k+XQszhf5/UgX2nhWegh+QxTx3xQmRGIrgC/x/NP9AjZSgN5
  8mOPAHhql5eLaAwDTKtXywzTAdnRralAEzPSL6ES1UPe7olCkrlRGi9reN6tdS50
  LK8xM/7Y0WDs199HA3HL6Y2jBh8vep148fzTPMt6h0agJBdSyeHyY4wHjNNoKe3h
  uxgANhoD3jhyrj140aBsw6X7Mlq7+SOQ98YFGTrTbyW4wvDfkF5QQhLgNHAqASmA
  X1KiZykq/sm+G/i9TidatJVkVfqCy766ZUX3TiwXSE+yWTWgEbKaL4/qgVC00xwb
  BvJj2b9c8GzhAT4YbcZyBINXazJaHXPdTnzVij7Q88OSITlojACSmxXDNLetgl1K
  ztz1PF+faWVkfwbYrDQHz9t5ir7iEPGAt7MLYBbvoKSmb1dHhRoQEkeTN1CSmp59
  3gRRNkGt6G90TteqhbIxI4tQ4OVwxczrEQsN7mw+jdDhh9EWi2kjlxn2X+hUd4NW
  6k93TXtkwUOuqlmHEZzThJH7BMG4qMLC9dWUDdRWAcLEi3Tsbe0rU6YoD2d5J4Bc
  qdmoUWHZH71oOcrg6HwdGSctAglfihrXFSerBxBHbGxqtXU5+04oiu0OuQINBFYB
  lC4BEADGnkNvBjXri8dBKsqBAJ3IHj64e8Md+TdHzItJ+7OdO4jJ5KHhdWfhfLK8
  6tOQpn2xDJF3zKS4WnKKbjc3XM9tmtqXwjmhCMHvp+IeHnliYBFT/dRqad0q36Wm
  7kbO+SEJCICAdtDw9Ud6w9NijVID6dPl152WM9tjDApCSXmu4Zd8hk48rG8NlJaw
  5AuW2/sfAFNPj3y44OZzCrJ2EOFl0yeMu4Oei51tImM0yQ/faz97zXkTrZGLDpq+
  XSlil1kj7wWFB84+mShVHzs3tJkdwwMftnIzs0AjeICVxqHnE/R/c08u+FdaNpOc
  AsWNr8mWAcQfYLZwgrJfz4e6IOS9v8IavTyZz0VWzbrbj8SgJ5jM9g504n/ftcOf
  8zAR1Qw5tlg1ACdN7eOtmtWHK2Ay/mckM560FmXLrFMLvFw4MIjZEdLL2rxKEJzB
  vcTl2rWJTATGymap+esJRIeFgN+FEZxqhf35xJ98Hej/GgNwqwf67aD6S1qkE0kI
  2LcLoXyLVARcmzlMGABw152QWDXm38M1nSFtREn4DujlJECC4cljpHzFXYMVJv6J
  vNtKSsbjVhncmlHRC2fsbr+kSs7LEF3w0INDT1XTJnzMnYclpJBjlN67YG5XnxKd
  ylNIYkYY2t3SPVCgT7RzF5/qsaeP2Sivrl/lf0ku7XAxfnAIYQARAQABiQIlBBgB
  AgAPBQJWAZQuAhsMBQkSzAMAAAoJEGv8pyAAarLeG2UQAM1/RliyIIAfbVTM3wA4
  l9nuDnPzcrn4zTiwBXPzQz2l05dDhyMNdlFrF7Jh29hWVPhLgjQlNSntG0pUaGqe
  ME/7mrTenSiMPGIJlmBmg3BwXCkHbAqFMU+ETzKAruTZHsG3z2venQtICXwLzGHE
  EGQiHO/bz1bYNt/8cUpd0xuaoCKG3EqkqjhP+pzcdknx+VR5h/wvW8dyDqrv8YHX
  VvNNbDohBOM/JlwAV9FppoDfUNnWBoz6vhulnUeeIi1Bcthse+r3VKes8Id6R6uD
  aOuMHeJ9taOw78twgGwgXL0qFqXkMlKOweeiwDtGhh9ffmxYKQA+YkWJ5lfYy2sy
  vdSoaVZUFz6aSbWgxjYZiCVK/ykqlpHFAC3RMbvRVnCdDlTFF7rMeh68bYtvpURH
  CNJS5a8uCDfQjQOGwWZcHCz6oPmF6AcRW4GNBqky5Vhvi9YTs0o3KJHRui5NRH6M
  bT71KVlERr/Smv/W+SLUmsYgy54yolkTbLQGWlvxY4S4SnMESNWcHQO0IJsHRcpY
  CNQTXiJ3Fb4LF+QH/ZOE5vT68B2jw6zEXEi5Kvavi05oQPI0smAUhxpJ2P1X3cON
  TobZR+Xe7IkwtEjFyBlO9kPtV9XEzIoqtizY0587iydpy2NmGyO8x3SZMLn9worF
  m+F9pb6PGO4FjLyFIzevuz2r
  =VWqr
  -----END PGP PUBLIC KEY BLOCK-----


