inherit_gem:
  rubocop-rails_config:
  rubocop-performance:
AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - '**/bin/**/*'
    - 'vendor/**/*'
    - 'gemfiles/vendor/**/*'
    - 'spec/dummy/db/schema.rb'
    - 'db/**/*'
    - 'test/**/**/*'
    - 'spec/**/**/*'
    - 'config/**/**/*'
    - 'Backup/**/**/*'
    - 'lib/tasks/**/**/*'
    - 'Guardfile'
    - 'Gemfile'
    - 'Vagrantfile'
    - '**/*.jbuilder'
Rails:
  Enabled: true

Performance:
  enabled: true

Rails/Validation:
  Enabled: true

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedLastArgumentHashStyle: always_ignore

Style/Lambda:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: rails

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: true

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/SignalException:
  EnforcedStyle: only_raise

Style/NumericLiterals:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/ClassAndModuleChildren:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Metrics/AbcSize:
  Max: 25

Metrics/LineLength:
  Enabled: false

