inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-faker
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  DisabledByDefault: false
  NewCops: enable
