inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  DisabledByDefault: false
  NewCops: enable
  UseCache: enable

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Metrics/CyclomaticComplexity:
  Severity: warning

Layout/LineLength: 
  Severity: warning
