language: ruby
cache: bundler
sudo: required
dist: bionic
bundler_args: "--jobs=4 --retry=3"
addons: # get google-chrome-stable
  chrome: stable
services:
  - redis
  - mysql
before_script:
  - bundle exec rake db:migrate RAILS_ENV=test
addons:
  code_climate:
    repo_token: bc9e0fee3d10d7a24d762909e4fffe85dab761dfded5db6ffddf9d7b6e5b61f4
install: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
