SECRET_KEY_BASE: "thisisasupersecret"
WUFOO_HANDSHAKE_KEY: ""
GIBBON_API_KEY: ""
TWILIO_API_SID: ""
TWILIO_API_TOKEN: ""
TWILIO_ACCOUNT_SID: ""
TWILIO_AUTH_TOKEN: ""
TWILIO_NUMBER: ""
WUFOO_ACCOUNT: ""
WUFOO_API: ""
WUFOO_SIGNUP_FORM: ""
WUFOO_HANDSHAKE_KEY: ""
MAILCHIMP_API_KEY: ""
MAILCHIMP_LIST_ID: ""
PRODUCTION_SERVER: "example.com"
PRODUCTION_BRANCH: "master"
STAGING_SERVER: "staging.example.com"
STAGING_BRANCH: "devlopment"
GIT_REPOSITORY: "git@github.com:example/example.git"
TIME_ZONE: "Central Time (US & Canada)"