# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ac5052e6fb90294106aaa35b69f2e784cdc87ab586b8cd34e47575f24217737198ea3a9bbb115e6c9b7e206fbdea6bf5b29bebb489aed69a23c68c7313a3b699

test:
  secret_key_base: be233f230b11192c9a3d2d31f896879cbb6146b3c0bdf75e235e253c09571cf77ed0779e0c1b9a126a3e828c8926a080f366ef990d1f8dc590a68a1acb870fbb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
