development:
  :concurrency: 5
production:
  :concurrency: <%= ENV['RAILS_MAX_THREADS'] || 25 %>
:queues:
  - ['rapidpro',3]
  - ['default',2]
  - ['mailers',1]
  - ['action_mailbox_routing',2]
  - ['action_mailbox_incineration',9]
  - ['active_storage_analysis',1]
  - ['active_storage_purge',10]
