development:
  :concurrency: 5
production:
  :concurrency: <%= ENV['RAILS_MAX_THREADS'] || 25 %>
:queues:
  - rapidpro
  - default
  - mailers
  - cron
  - action_mailbox_routing
  - action_mailbox_incineration
  - active_storage_analysis
  - active_storage_purge
:schedule:
  BackupJob:
    cron: '0 0 2 * * *' # everyday at 2am

  DailyUserRemindersJob:
    cron: '0 0 8 * * *'

  DailyParticipationLevelUpdateJob:
    cron: '0 0 0 * * *' # everyday at midnight
