development:
  :concurrency: 5
production:
  :concurrency: <%= ENV['RAILS_MAX_THREADS'] || 25 %>
:queues:
  - rapidpro
  - default
  - mailers
  - action_mailbox_routing
  - action_mailbox_incineration
  - active_storage_analysis
  - active_storage_purge
