name: Ruby

on: [push, pull_request]

jobs:
  services:
    mysql:
      image: mysql:5.7
      env:
        MYSQL_ROOT_PASSWORD: root
      ports:
      - 3306
      options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    # How to use Redis
    redis:
      image: redis
      ports:
      - 6379/tcp
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: bundle install -j 4
    - name: Run tests
      run: bundle exec rake
